name: Deploy Documentation to Pages
run-name: ${{ github.actor }} triggered a documentation publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clone current commit
        uses: actions/checkout@v3
      - name: Execute Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/dokka/html
  deploy:
    # Add a dependency to the build job
    needs: generate

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
