name: Gradle Build
run-name: ${{ github.actor }} is running a build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
      - name: Execute Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
